# This is a basic workflow to help you get started with Actions

name: Copy to Portfolio and Push to Netlify

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  directory:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout p1
      uses: actions/checkout@v2
    
    - name: Copycat Directory
      uses: andstor/copycat-action@v3.0.0
      with:
          personal_token: ${{ secrets.PORTFOLIO_SECRET }}
          src_path: public/*
          dst_path: work/pantone-picker/
          dst_owner: franknoirot
          dst_repo_name: franknoirot.co
  
  config:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: directory

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout p2
      uses: actions/checkout@v2

    - name: Copycat Config
      uses: andstor/copycat-action@v3.0.0
      with:
          personal_token: ${{ secrets.PORTFOLIO_SECRET }}
          src_path: portfolio-config.json
          dst_path: _data/work/pantonePicker.json
          dst_owner: franknoirot
          dst_repo_name: franknoirot.co
